# Generated by Django 3.0.6 on 2020-07-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('switch', 'Switch'), ('firewall', 'Firewall'), ('router', 'Router')], default='router', max_length=30),
        ),
    ]
