# Generated by Django 3.0.6 on 2020-07-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='protocol',
            field=models.CharField(blank=True, choices=[('ospf', 'OSPF'), ('eigrp', 'EIGRP'), ('bgp', 'BGP')], default='bgp', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall')], default='router', max_length=30),
        ),
    ]
