# Generated by Django 3.0.6 on 2020-07-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_manager', '0003_auto_20200726_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('firewall', 'Firewall'), ('switch', 'Switch'), ('router', 'Router')], default='router', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='plateform',
            field=models.CharField(blank=True, choices=[('cisco_iosxe', 'CISCO IOS XE'), ('cisco_ios', 'CISCO IOS')], default='cisco_ios', max_length=30),
        ),
        migrations.AlterField(
            model_name='vrf',
            name='routing',
            field=models.CharField(blank=True, choices=[('ospf', 'OSPF'), ('static', 'STATIC ROUTAGE'), ('eigrp', 'EIGRP'), ('rip', 'RIP version 2')], default='static', max_length=30),
        ),
    ]
