# Generated by Django 3.0.6 on 2020-07-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_manager', '0004_auto_20200730_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='pseudowire',
            name='vcid',
            field=models.IntegerField(default=101),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('switch', 'Switch'), ('router', 'Router'), ('firewall', 'Firewall')], default='router', max_length=30),
        ),
        migrations.AlterField(
            model_name='pseudowire',
            name='encapsulation',
            field=models.CharField(blank=True, choices=[('l2tpv2 ', 'L2TPv2 encapsulation'), ('mpls', 'MPLS encapsulation'), ('l2tpv3', 'L2TPv3 encapsulation')], default='mpls', max_length=30),
        ),
    ]
