# Generated by Django 3.0.6 on 2020-07-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_manager', '0005_auto_20200730_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('router', 'Router'), ('firewall', 'Firewall'), ('switch', 'Switch')], default='router', max_length=30),
        ),
        migrations.AlterField(
            model_name='pseudowire',
            name='encapsulation',
            field=models.CharField(blank=True, choices=[('l2tpv3', 'L2TPv3 encapsulation'), ('l2tpv2 ', 'L2TPv2 encapsulation'), ('mpls', 'MPLS encapsulation')], default='mpls', max_length=30),
        ),
        migrations.AlterField(
            model_name='pseudowire',
            name='vcid',
            field=models.IntegerField(default=101),
        ),
    ]
