# Generated by Django 3.0.6 on 2020-07-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_manager', '0006_auto_20200730_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('switch', 'Switch'), ('firewall', 'Firewall'), ('router', 'Router')], default='router', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='plateform',
            field=models.CharField(blank=True, choices=[('cisco_iosxe', 'CISCO IOS XE'), ('cisco_ios', 'CISCO IOS')], default='cisco_ios', max_length=30),
        ),
        migrations.AlterField(
            model_name='pseudowire',
            name='encapsulation',
            field=models.CharField(blank=True, choices=[('mpls', 'MPLS encapsulation'), ('l2tpv3', 'L2TPv3 encapsulation'), ('l2tpv2 ', 'L2TPv2 encapsulation')], default='mpls', max_length=30),
        ),
        migrations.CreateModel(
            name='Vpls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('vcid', models.IntegerField(default=101)),
                ('router', models.ManyToManyField(blank=True, related_name='device_vpls', to='mpls_manager.Device')),
            ],
        ),
    ]
