# Generated by Django 3.0.6 on 2020-07-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_manager', '0007_auto_20200730_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='loopback',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('firewall', 'Firewall'), ('router', 'Router'), ('switch', 'Switch')], default='router', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='plateform',
            field=models.CharField(blank=True, choices=[('cisco_ios', 'CISCO IOS'), ('cisco_iosxe', 'CISCO IOS XE')], default='cisco_ios', max_length=30),
        ),
        migrations.AlterField(
            model_name='pseudowire',
            name='encapsulation',
            field=models.CharField(blank=True, choices=[('l2tpv3', 'L2TPv3 encapsulation'), ('l2tpv2 ', 'L2TPv2 encapsulation'), ('mpls', 'MPLS encapsulation')], default='mpls', max_length=30),
        ),
    ]
