# Generated by Django 3.0.6 on 2020-07-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_manager', '0008_auto_20200730_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('router', 'Router'), ('firewall', 'Firewall'), ('switch', 'Switch')], default='router', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='loopback',
            field=models.CharField(max_length=100),
        ),
    ]
