# Generated by Django 3.0.6 on 2020-07-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_manager', '0009_auto_20200730_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('switch', 'Switch'), ('firewall', 'Firewall'), ('router', 'Router')], default='router', max_length=30),
        ),
        migrations.AlterField(
            model_name='pseudowire',
            name='encapsulation',
            field=models.CharField(blank=True, choices=[('l2tpv2 ', 'L2TPv2 encapsulation'), ('mpls', 'MPLS encapsulation'), ('l2tpv3', 'L2TPv3 encapsulation')], default='mpls', max_length=30),
        ),
    ]
