FROM python:3.7-slim
LABEL maintainer="Baba Sangare <sibrahima250@gmail.com>"
WORKDIR /app

RUN apt-get clean && apt-get update


RUN apt-get update \
    && apt install curl\
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    
COPY poetry.lock pyproject.toml /code/

RUN python -m venv .venv


EXPOSE 3000


WORKDIR smart_mpls

CMD ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:3000"]