version: "3.3"

services:
  django:
    command: sh -c "wait-for python manage.py migrate && python manage.py runserver 0.0.0.0:3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
