version: "3.3"

services:
  django:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python testconfig.py 
    volumes:
      - ./smart_mpls:/code 
    ports:
      - "8000:8000"
    
  #====================================#
  #services:
  #  django:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    container_name: django
  #    image: smart_mpls:dev
  #    environment:
  #      - PYTHONUNBUFFERED=1
  #    volumes:
  #      - ./log:/log
  #    command: python manage.py runserver 0.0.0.0:3000
  #    ports:
  #      - "3000:3000"
  #  redis:
  #    image: redis:4-alpine
  #    restart: on-failure
  #    container_name: redis
  #    sysctls:
  #      net.core.somaxconn: "511"
  #    volumes:
  #      - ./data:/data
#  celery:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        STATIC_URL: "/static/"
#    container_name: celery
#    image: smart_mpls
#    command: >-
#      poetry run celery worker
#      -A smart_mpls#
#      --loglevel=info --pool=gevent --concurrency=15
#    volumes:
#      - ./log:/log
#      - ./smart_mpls:/app/smart_mpls
#    depends_on:
#      - redis
#======================================
#  celery:
#    build:
#      dockerfile: Dockerfile-dev
#    container_name: celery
#    image: netprog-stream-django:dev
#    command: >-
#      poetry run celery worker
#      -A smart_mpls
#      --loglevel=info --pool=gevent --concurrency=15
#    volumes:
#      - ./log:/log
#      - ./smart_mpls:/app/smart_mpls
#    depends_on:
#      - redis
