# Generated by Django 3.0.6 on 2020-07-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, choices=[('firewall', 'Firewall'), ('router', 'Router'), ('switch', 'Switch')], default='router', max_length=30)),
                ('plateform', models.CharField(blank=True, choices=[('cisco_ios', 'CISCO IOS'), ('cisco_iosxe', 'CISCO IOS XE')], default='cisco_ios', max_length=30)),
            ],
        ),
    ]
