# Generated by Django 3.0.6 on 2020-07-22 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('router', 'Router'), ('firewall', 'Firewall'), ('switch', 'Switch')], default='router', max_length=30),
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingress', models.BooleanField(default=False)),
                ('egress', models.BooleanField(default=False)),
                ('backbone', models.BooleanField(default=False)),
                ('device_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mpls_monitor.Device')),
            ],
        ),
    ]
