# Generated by Django 3.0.6 on 2020-07-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_monitor', '0002_auto_20200722_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vrf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rd', models.CharField(max_length=255)),
                ('routeImport', models.CharField(max_length=255)),
                ('routeExport', models.CharField(max_length=255)),
                ('routing', models.CharField(blank=True, choices=[('rip', 'RIP version 2'), ('static', 'STATIC'), ('eigrp', 'EIGRP'), ('ospf', 'OSPF')], default='ospf', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='plateform',
            field=models.CharField(blank=True, choices=[('cisco_iosxe', 'CISCO IOS XE'), ('cisco_ios', 'CISCO IOS')], default='cisco_ios', max_length=30),
        ),
    ]
