# Generated by Django 3.0.6 on 2020-07-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_monitor', '0003_auto_20200722_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrf',
            name='routing',
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('firewall', 'Firewall'), ('switch', 'Switch'), ('router', 'Router')], default='router', max_length=30),
        ),
    ]
