# Generated by Django 3.0.6 on 2020-07-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_monitor', '0004_auto_20200723_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='password',
        ),
        migrations.RemoveField(
            model_name='device',
            name='username',
        ),
        migrations.AddField(
            model_name='device',
            name='management',
            field=models.ManyToManyField(blank=True, related_name='device', to='mpls_monitor.Access'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall')], default='router', max_length=30),
        ),
    ]
