# Generated by Django 3.0.6 on 2020-07-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_monitor', '0006_auto_20200724_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='management',
            field=models.ManyToManyField(blank=True, related_name='device', to='mpls_monitor.Access'),
        ),
        migrations.AddField(
            model_name='device',
            name='topology_ref',
            field=models.ManyToManyField(blank=True, related_name='device', to='mpls_monitor.Topologies'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('switch', 'Switch'), ('router', 'Router'), ('firewall', 'Firewall')], default='router', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='plateform',
            field=models.CharField(blank=True, choices=[('cisco_ios', 'CISCO IOS'), ('cisco_iosxe', 'CISCO IOS XE')], default='cisco_ios', max_length=30),
        ),
    ]
