# Generated by Django 3.0.6 on 2020-07-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_monitor', '0007_auto_20200724_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall')], default='router', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='plateform',
            field=models.CharField(blank=True, choices=[('cisco_iosxe', 'CISCO IOS XE'), ('cisco_ios', 'CISCO IOS')], default='cisco_ios', max_length=30),
        ),
    ]
